### ISSUE TITLE
Season Three (1.18 Migration)

### ISSUE THREAD

**Issue by RWELabs** [RWELabs/Minecraft#6]
The following tasks need to be completed in order for Season Three to commence.

- [x] Migrate server host to new location
- [x] Convert Skyblock map to vanilla world save from Spigot
- [x] Wipe server whitelist
- [x] Clear server backups
- [x] Clear CubedHost panel before Dec 12 billing period
- [x] Update plugins to latest 1.18 compatible versions
- [x] Generate new world with world seed
- [x] Set world border (5k, 7k, 10k?)
- [x] Pre-generate chunks from spawn outward toward world border.
- [x] Perform full Dynmap render
- [x] Revisit Paper YML + other configuration files for new features.
- [x] Announce S3 intentions.
- [x] Update CrutioBot code to support S3 whitelisting
- [x] Re-Enable CrutioBot whitelisting commands
- [x] Test CrutioBot whitelisting commands
- [x] Open whitelist registrations to players
- [x] Write server rules and information channel draft
- [x] Update datapacks to latest versions
- [x] Create Season 3 hero image
- [x] Review other plugin permissions
- [x] Review permissions with LuckPerms
- [x] Ensure redstone, bedrock breaking + tnt duping are enabled.
- [x] Test stability of Paper builds

**Comment by Crutionix** [comment]
Pre-generating chunks has started. Trying to alternate between generating chunks and dynmap rendering as they are both CPU intensive tasks.

Generated to 6k blocks, dynmap rendered to 6k blocks. World border set to 7.5k blocks.

**Comment by Crutionix** [comment]
Generated to 6k blocks, dynmap rendered to 6k blocks. World border set to 7.5k blocks.

**Comment by Crutionix** [comment]
Pre-Launch Procedures
- [x] Mark down hyper specific reserved areas with signs/torches
- [x] Clear advancements and player data from admins 
- [x] Clear local difficulty and reset time
- [x] Reset difficulty as well as daytime and weather cycles.
- [x] Construct additional pylons.
